// packages/svelte/src/lib/auth/interfaces/VerifyOtp.svelte
<script lang="ts">
	import type {
		EmailOtpType,
		MobileOtpType,
		SupabaseClient,
		VerifyOtpParams
	} from '@supabase/supabase-js';

	import Button from '$lib/ui/Button.svelte';
	import Container from '$lib/ui/Container.svelte';
	import Input from '$lib/ui/Input.svelte';
	import Label from '$lib/ui/Label.svelte';
	import Message from '$lib/ui/Message.svelte';
	import Anchor from '$lib/ui/Anchor.svelte';

	import { type I18nVariables, ViewType, type OtpType } from '@supabase/auth-ui-shared';

	export let i18n: I18nVariables;
	export let supabaseClient: SupabaseClient;
	export let authView: ViewType;
	export let otpType: OtpType = 'email';
	export let showLinks = false;
	export let email = '';
	export let phone = '';
	export let token = '';

	let message = '';
	let error = '';
	let loading = false;

	async function handleSubmit() {
		loading = true;
		error = '';
		message = '';

		let verifyOpts: VerifyOtpParams = {
			email,
			token,
			type: otpType as EmailOtpType
		};
		if (['sms', 'phone_change'].includes(otpType)) {
			verifyOpts = {
				phone,
				token,
				type: otpType as MobileOtpType
			};
		}
		const { error: err } = await supabaseClient.auth.verifyOtp(verifyOpts);
		if (err) error = err.message;
		loading = false;
	}
</script>

<form id="auth-magic-link" method="post" on:submit|preventDefault={handleSubmit}>
	<Container direction="vertical" gap="large">
		{#if ['sms', 'phone_change'].includes(otpType)}
			<div>
				<Label for="phone">{i18n?.verify_otp?.phone_input_label}</Label>
				<Input
					id="phone"
					type="text"
					name="phone"
					autofocus
					placeholder={i18n?.verify_otp?.phone_input_placeholder}
					bind:value={phone}
					autocomplete="phone"
				/>
			</div>
		{:else}
			<div>
				<Label for="email">{i18n?.verify_otp?.email_input_label}</Label>
				<Input
					id="email"
					type="email"
					name="email"
					autofocus
					placeholder={i18n?.verify_otp?.email_input_placeholder}
					bind:value={email}
					autocomplete="email"
				/>
			</div>
		{/if}
		<div>
			<Label for="token">{i18n?.verify_otp?.token_input_label}</Label>
			<Input
				id="token"
				type="text"
				name="token"
				placeholder={i18n?.verify_otp?.token_input_placeholder}
				bind:value={token}
				autocomplete="token"
			/>
		</div>
		<Button type="submit" color="primary" {loading}>
			{i18n?.verify_otp?.button_label}
		</Button>

		{#if showLinks}
			<Anchor
				on:click={(e) => {
					e.preventDefault();
					authView = ViewType.SignIn;
				}}
				href="#auth-sign-in">{i18n?.sign_in?.link_text}</Anchor
			>
		{/if}
		{#if message}
			<Message>
				{message}
			</Message>
		{/if}
		{#if error}
			<Message color="danger">
				{error}
			</Message>
		{/if}
	</Container>
</form>

<style>
	form {
		width: 100%;
	}
</style>

// packages/react/src/lib/auth/interfaces/VerifyOtp.tsx
import {
  EmailOtpType,
  MobileOtpType,
  SupabaseClient,
  VerifyOtpParams,
} from '@supabase/supabase-js';
import React, { useState } from 'react';
import { I18nVariables, OtpType, VIEWS } from '@supabase/auth-ui-shared';
import { Anchor, Button, Container, Input, Label, Message } from './../../ui';

function VerifyOtp({
  setAuthView = () => {},
  supabaseClient,
  otpType = 'email',
  i18n,
  showLinks = false,
}: {
  setAuthView?: any;
  supabaseClient: SupabaseClient;
  otpType: OtpType;
  i18n?: I18nVariables;
  showLinks?: boolean;
}) {
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [token, setToken] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError('');
    setMessage('');
    setLoading(true);

    let verifyOpts: VerifyOtpParams = {
      email,
      token,
      type: otpType as EmailOtpType,
    };
    if (['sms', 'phone_change'].includes(otpType)) {
      verifyOpts = {
        phone,
        token,
        type: otpType as MobileOtpType,
      };
    }
    const { error } = await supabaseClient.auth.verifyOtp(verifyOpts);
    if (error) setError(error.message);
    setLoading(false);
  };

  const labels = i18n?.verify_otp;

  return (
    <form method="post" id="auth-magic-link" onSubmit={handleSubmit}>
      <Container gap="large" direction="vertical">
        {['sms', 'phone_change'].includes(otpType) ? (
          <div>
            <Label htmlFor="phone">{labels?.phone_input_label}</Label>
            <Input
              id="phone"
              name="phone"
              type="text"
              autoFocus
              placeholder={labels?.phone_input_placeholder}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPhone(e.target.value)}
            />
          </div>
        ) : (
          <div>
            <Label htmlFor="email">{labels?.email_input_label}</Label>
            <Input
              id="email"
              name="email"
              type="email"
              autoFocus
              placeholder={labels?.email_input_placeholder}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
            />
          </div>
        )}
        <div>
          <Label htmlFor="token">{labels?.token_input_label}</Label>
          <Input
            id="token"
            name="token"
            type="text"
            placeholder={labels?.token_input_placeholder}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => setToken(e.target.value)}
          />
        </div>
        <Button color="primary" type="submit" loading={loading}>
          {loading ? labels?.loading_button_label : labels?.button_label}
        </Button>
        {showLinks && (
          <Anchor
            href="#auth-sign-in"
            onClick={(e: React.MouseEvent<HTMLAnchorElement>) => {
              e.preventDefault();
              setAuthView(VIEWS.SIGN_IN);
            }}
          >
            {i18n?.sign_in?.link_text}
          </Anchor>
        )}
        {message && <Message>{message}</Message>}
        {error && <Message color="danger">{error}</Message>}
      </Container>
    </form>
  );
}

export { VerifyOtp };
