// packages/svelte/src/lib/Auth.svelte
<script lang="ts">
	import ForgottenPassword from './ui/ForgottenPassword.svelte';
	import MagicLink from './ui/MagicLink.svelte';
	import UpdatePassword from './ui/UpdatePassword.svelte';
	import VerifyOtp from './ui/VerifyOtp.svelte';
	import Signin from './ui/Signin.svelte';
	import Signup from './ui/Signup.svelte';
	import type { AuthViewType, OtpType } from '@supabase/auth-ui-shared';

	export let view: AuthViewType = 'sign_in';
	export let otpType: OtpType = 'email';
	export let redirectTo: string | undefined = undefined;
</script>

{#if view === 'sign_in'}
	<Signin {redirectTo} />
{:else if view === 'sign_up'}
	<Signup {redirectTo} />
{:else if view === 'magic_link'}
	<MagicLink {redirectTo} />
{:else if view === 'forgotten_password'}
	<ForgottenPassword {redirectTo} />
{:else if view === 'update_password'}
	<UpdatePassword />
{:else if view === 'verify_otp'}
	<VerifyOtp {otpType} />
{/if}

// packages/react/src/lib/Auth.tsx
import { AuthViewType, OtpType, RedirectTo } from '@supabase/auth-ui-shared';

import ForgottenPassword from './ui/ForgottenPassword';
import MagicLink from './ui/MagicLink';
import UpdatePassword from './ui/UpdatePassword';
import VerifyOtp from './ui/VerifyOtp';
import Signin from './ui/Signin';
import Signup from './ui/Signup';

export default function Auth({
	view = 'sign_in',
	otpType = 'email',
	redirectTo,
}: {
	view?: AuthViewType;
	otpType?: OtpType;
	redirectTo?: RedirectTo;
}) {
	switch (view) {
		case 'sign_in':
			return <Signin redirectTo={redirectTo}></Signin>;
		case 'sign_up':
			return <Signup redirectTo={redirectTo}></Signup>;
		case 'magic_link':
			return <MagicLink redirectTo={redirectTo}></MagicLink>;
		case 'forgotten_password':
			return <ForgottenPassword redirectTo={redirectTo}></ForgottenPassword>;
		case 'update_password':
			return <UpdatePassword redirectTo={redirectTo}></UpdatePassword>;
		case 'verify_otp':
			return <VerifyOtp otpType={otpType} redirectTo={redirectTo}></VerifyOtp>;
	}
}
