// packages/react/src/lib/interfaces/SocialAuth.tsx
import { Provider } from '@supabase/supabase-js';
import { useState } from 'react';
import { template, RedirectTo } from '@supabase/auth-ui-shared';
import { Button, Container } from '../components';
import * as SocialIcons from '../ProviderIcons.js';
import { useSupabaseContext } from '../SupabaseProvider.js';

function SocialAuth({ redirectTo }: { redirectTo?: RedirectTo }) {
	const [loading, setLoading] = useState(false);
	const [, setError] = useState('');

	const {
		supabaseClient,
		i18n,
		appearence: { socialLayout },
		config: { redirectTo: _redirectTo, providerScopes, providerQueryParams, providers = [] },
	} = useSupabaseContext();

	const handleProviderSignIn = async (provider: Provider) => {
		setLoading(true);
		const { error } = await supabaseClient.auth.signInWithOAuth({
			provider,
			options: {
				redirectTo,
				scopes: providerScopes?.[provider],
				queryParams: providerQueryParams,
			},
		});
		if (error) setError(error.message);
		setLoading(false);
	};

	function capitalize(word: string) {
		const lower = word.toLowerCase();
		return word.charAt(0).toUpperCase() + lower.slice(1);
	}

	return (
		providers?.length > 0 && (
			<Container direction={socialLayout} gap={socialLayout === 'vertical' ? 'small' : 'medium'}>
				{providers.map((provider: Provider) => {
					// @ts-ignore
					const AuthIcon = SocialIcons[provider] as () => JSX.Element;
					return (
						<Button
							key={provider}
							color="default"
							icon={AuthIcon ? <AuthIcon /> : ''}
							loading={loading}
							onClick={() => handleProviderSignIn(provider)}
						>
							{socialLayout === 'vertical' &&
								template(i18n?.['sign_in']?.social_provider_text as string, {
									provider: capitalize(provider),
								})}
						</Button>
					);
				})}
			</Container>
		)
	);
}

export { SocialAuth };

// packages/svelte/src/lib/interfaces/SocialAuth.svelte
<script lang="ts">
	import type { Provider } from '@supabase/supabase-js';
	import { template } from '@supabase/auth-ui-shared';

	import { Button, Container } from '../components/index.js';
	import ProviderIcon from '../ProviderIcon.svelte';
	import { getSupabaseContext } from '../SupabaseProvider.svelte';

	const {
		supabaseClient,
		i18n,
		config: { providers = [], providerScopes, providerQueryParams, redirectTo: _redirectTo },
		appearence: { socialLayout }
	} = getSupabaseContext();

	export let redirectTo: string | undefined = _redirectTo;

	let error = '';
	let loading = false;

	$: verticalSocialLayout = socialLayout === 'vertical' ? true : false;

	async function handleProviderSignIn(provider: Provider) {
		loading = true;
		error = '';
		const { error: providerSigninError } = await supabaseClient.auth.signInWithOAuth({
			provider,
			options: {
				redirectTo,
				scopes: providerScopes?.[provider],
				queryParams: providerQueryParams
			}
		});
		if (providerSigninError) error = providerSigninError.message;
		loading = false;
	}

	function capitalize(word: string) {
		return word[0].toUpperCase() + word.slice(1).toLowerCase();
	}

	let iconTitle = (provider: string) =>
		template(i18n['sign_in']?.social_provider_text as string, {
			provider: capitalize(provider)
		});
</script>

{#if providers.length}
	<Container
		direction={verticalSocialLayout ? 'vertical' : 'horizontal'}
		gap={verticalSocialLayout ? 'small' : 'medium'}
	>
		{#each [...new Set(providers)] as provider}
			<Button
				aria-label={iconTitle(provider)}
				on:click={() => handleProviderSignIn(provider)}
				type="submit"
				color="default"
				{loading}
			>
				<ProviderIcon {provider} />
				{#if verticalSocialLayout}
					{iconTitle(provider)}
				{/if}
			</Button>
		{/each}
	</Container>
{/if}
