// packages/react/src/lib/ui/Signup.tsx
import { RedirectTo } from '@supabase/auth-ui-shared';
import { useSupabaseContext } from '../SupabaseProvider';
import Theme from '../Theme';
import { EmailAuth, SocialAuth } from '../interfaces';
import { Message } from '../components';

export default function Signup({ redirectTo }: { redirectTo?: RedirectTo }) {
	const {
		config: { email_enabled = true, disable_signup = false, providers },
	} = useSupabaseContext();

	return (
		<Theme>
			{disable_signup ? (
				<Message>Signup is disabled.</Message>
			) : (
				<>
					{providers?.length && <SocialAuth redirectTo={redirectTo} />}
					{email_enabled && <EmailAuth authView="sign_up" redirectTo={redirectTo} />}
				</>
			)}
		</Theme>
	);
}

// packages/svelte/src/lib/ui/Signup.svelte
<script lang="ts">
	import { getSupabaseContext } from '../SupabaseProvider.svelte';
	import Theme from '../Theme.svelte';
	import Message from '../components/Message.svelte';
	import EmailAuth from '../interfaces/EmailAuth.svelte';
	import SocialAuth from '../interfaces/SocialAuth.svelte';

	export let redirectTo: string | undefined = undefined;

	const {
		config: { email_enabled = true, providers, disable_signup }
	} = getSupabaseContext();
</script>

<Theme>
	{#if disable_signup}
		<Message>Signup is disabled.</Message>
	{:else}
		{#if providers?.length}
			<SocialAuth {redirectTo} />
		{/if}

		{#if email_enabled}
			<EmailAuth authView="sign_up" {redirectTo} />
		{/if}
	{/if}
</Theme>
