// packages/svelte/src/lib/ui/ForgottenPassword.svelte
<script lang="ts">
	import Theme from '../Theme.svelte';
	import { Button, Container, Input, Label, Message, AuthLink } from '../components/index.js';
	import { getSupabaseContext } from '../SupabaseProvider.svelte';

	const {
		supabaseClient,
		i18n,
		config: { redirectTo: _redirectTo }
	} = getSupabaseContext();

	export let redirectTo: string | undefined = _redirectTo;

	let email = '';
	let message = '';
	let error = '';
	let loading = false;

	async function handleSubmit() {
		loading = true;
		error = '';
		message = '';
		const { error: resetPasswordError } = await supabaseClient.auth.resetPasswordForEmail(email, {
			redirectTo
		});
		if (resetPasswordError) error = resetPasswordError.message;
		else message = i18n.forgotten_password?.confirmation_text as string;
		loading = false;
	}
</script>

<Theme>
	<form id="auth-forgot-password" method="post" on:submit|preventDefault={handleSubmit}>
		<Container direction="vertical" gap="large">
			<Container direction="vertical" gap="large">
				<div>
					<Label for="email">{i18n?.forgotten_password?.email_label}</Label>
					<Input
						id="email"
						type="email"
						name="email"
						autofocus
						placeholder={i18n?.forgotten_password?.email_input_placeholder}
						bind:value={email}
						autocomplete="email"
					/>
				</div>
				<Button type="submit" color="primary" {loading}>
					{i18n?.forgotten_password?.button_label}
				</Button>
			</Container>

			<AuthLink view="sign_in" />

			{#if message}
				<Message>
					{message}
				</Message>
			{/if}
			{#if error}
				<Message color="danger">
					{error}
				</Message>
			{/if}
		</Container>
	</form>
</Theme>

<style>
	form {
		width: 100%;
	}
</style>

// packages/react/src/lib/ui/ForgottenPassword.tsx
import { RedirectTo } from '@supabase/auth-ui-shared';
import Theme from '../Theme';
import { useSupabaseContext } from '../SupabaseProvider';
import { useState } from 'react';
import { Button, Container, Input, Label, Message, AuthLink } from '../components';

export default function ForgottenPassword({ redirectTo }: { redirectTo?: RedirectTo }) {
	const {
		supabaseClient,
		i18n,
		config: { redirectTo: _redirectTo },
	} = useSupabaseContext();

	const [email, setEmail] = useState('');
	const [error, setError] = useState('');
	const [message, setMessage] = useState('');
	const [loading, setLoading] = useState(false);

	const handlePasswordReset = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		setError('');
		setMessage('');
		setLoading(true);
		const { error } = await supabaseClient.auth.resetPasswordForEmail(email, {
			redirectTo: redirectTo ?? _redirectTo,
		});
		if (error) setError(error.message);
		else setMessage(i18n?.forgotten_password?.confirmation_text as string);
		setLoading(false);
	};

	const labels = i18n?.forgotten_password;

	return (
		<Theme>
			<form method="post" id="auth-forgot-password" onSubmit={handlePasswordReset}>
				<Container gap="large" direction="vertical">
					<div>
						<Label htmlFor="email">{labels?.email_label}</Label>
						<Input
							id="email"
							name="email"
							type="email"
							autoFocus
							placeholder={labels?.email_input_placeholder}
							onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
						/>
					</div>

					<Button type="submit" color="primary" loading={loading}>
						{loading ? labels?.loading_button_label : labels?.button_label}
					</Button>

					<AuthLink view="sign_in"></AuthLink>

					{message && <Message>{message}</Message>}
					{error && <Message color="danger">{error}</Message>}
				</Container>
			</form>
		</Theme>
	);
}
