// packages/svelte/src/lib/ui/MagicLink.svelte
<script lang="ts">
	import {
		Button,
		Container,
		Divider,
		Input,
		Label,
		Message,
		AuthLink
	} from '$lib/components/index.js';
	import type { RedirectTo } from '@supabase/auth-ui-shared';
	import { getSupabaseContext } from '../SupabaseProvider.svelte';
	import Theme from '../Theme.svelte';
	import SocialAuth from '../interfaces/SocialAuth.svelte';

	const {
		supabaseClient,
		i18n,
		config: { email_enabled = true, providers, redirectTo: _redirectTo }
	} = getSupabaseContext();

	export let redirectTo: RedirectTo = _redirectTo;

	const labels = i18n.magic_link;
	let email = '';
	let message = '';
	let error = '';
	let loading = false;

	async function handleSubmit() {
		loading = true;
		error = '';
		message = '';
		const { error: resetPasswordError } = await supabaseClient.auth.signInWithOtp({
			email,
			options: {
				emailRedirectTo: redirectTo
			}
		});
		if (resetPasswordError) error = resetPasswordError.message;
		else message = labels?.confirmation_text as string;
		loading = false;
	}
</script>

<Theme>
	{#if providers?.length}
		<SocialAuth {redirectTo} />

		{#if email_enabled}
			<Divider />
		{/if}
	{/if}

	{#if email_enabled}
		<form id="auth-magic-link" method="post" on:submit|preventDefault={handleSubmit}>
			<Container direction="vertical" gap="large">
				<div>
					<Label for="email">{labels?.email_input_label}</Label>
					<Input
						id="email"
						type="email"
						name="email"
						autofocus
						placeholder={labels?.email_input_placeholder}
						bind:value={email}
						autocomplete="email"
					/>
				</div>

				<Button type="submit" color="primary" {loading}>
					{loading ? labels?.loading_button_label : labels?.button_label}
				</Button>

				<Container direction="vertical" gap="small">
					<AuthLink view="sign_in" />
				</Container>

				{#if message}
					<Message>{message}</Message>
				{/if}
				{#if error}
					<Message color="danger">{error}</Message>
				{/if}
			</Container>
		</form>
	{/if}
</Theme>

<style>
	form {
		width: 100%;
	}
</style>

// packages/react/src/lib/ui/MagicLink.tsx
import { RedirectTo } from '@supabase/auth-ui-shared';
import { useSupabaseContext } from '../SupabaseProvider';
import Theme from '../Theme';
import { SocialAuth } from '../interfaces';
import { Button, Container, Input, Label, Message, AuthLink, Divider } from '../components';
import { useState } from 'react';

export default function MagicLink({ redirectTo }: { redirectTo?: RedirectTo }) {
	const [email, setEmail] = useState('');
	const [error, setError] = useState('');
	const [message, setMessage] = useState('');
	const [loading, setLoading] = useState(false);

	const {
		supabaseClient,
		i18n,
		config: { redirectTo: _redirectTo, magic_link_enabled = true, providers },
	} = useSupabaseContext();

	const handleMagicLinkSignIn = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		setError('');
		setMessage('');
		setLoading(true);
		const { error } = await supabaseClient.auth.signInWithOtp({
			email,
			options: { emailRedirectTo: redirectTo ?? _redirectTo },
		});
		if (error) setError(error.message);
		else setMessage(i18n?.magic_link?.confirmation_text as string);
		setLoading(false);
	};

	const labels = i18n?.magic_link;

	return (
		<Theme>
			{providers?.length && (
				<>
					<SocialAuth redirectTo={redirectTo} />
					{magic_link_enabled && <Divider />}
				</>
			)}
			{magic_link_enabled && (
				<form method="post" id="auth-magic-link" onSubmit={handleMagicLinkSignIn}>
					<Container gap="large" direction="vertical">
						<div>
							<Label htmlFor="email">{labels?.email_input_label}</Label>
							<Input
								id="email"
								name="email"
								type="email"
								autoFocus
								placeholder={labels?.email_input_placeholder}
								onChange={(e: React.ChangeEvent<HTMLInputElement>) => setEmail(e.target.value)}
								defaultValue={email}
							/>
						</div>
						<Button color="primary" type="submit" loading={loading}>
							{loading ? labels?.loading_button_label : labels?.button_label}
						</Button>

						<Container direction="vertical" gap="small">
							<AuthLink view="sign_in"></AuthLink>
						</Container>

						{message && <Message>{message}</Message>}
						{error && <Message color="danger">{error}</Message>}
					</Container>
				</form>
			)}
		</Theme>
	);
}
