// packages/svelte/src/lib/ui/UpdatePassword.svelte
<script lang="ts">
	import Theme from '../Theme.svelte';

	import type { RedirectTo } from '@supabase/auth-ui-shared';
	import { Button, Container, Input, Label, Message, AuthLink } from '../components/index.js';
	import { getSupabaseContext } from '../SupabaseProvider.svelte';

	const {
		supabaseClient,
		i18n,
		config: { redirectTo: _redirectTo }
	} = getSupabaseContext();

	export let redirectTo: RedirectTo = _redirectTo;

	let password = '';
	let message = '';
	let error = '';
	let loading = false;

	async function handleSubmit() {
		loading = true;
		error = '';
		message = '';
		const { data, error: resetPasswordError } = await supabaseClient.auth.updateUser(
			{
				password
			},
			{
				emailRedirectTo: redirectTo
			}
		);
		if (resetPasswordError) error = resetPasswordError.message;
		else message = i18n.update_password?.confirmation_text as string;
		loading = false;
	}
</script>

<Theme>
	<form id="auth-update-password" method="post" on:submit|preventDefault={handleSubmit}>
		<Container direction="vertical" gap="large">
			<div>
				<Label for="password">
					{i18n?.update_password?.password_label}
				</Label>
				<Input
					id="password"
					type="password"
					name="password"
					autofocus
					placeholder={i18n?.update_password?.password_label}
					bind:value={password}
					autocomplete="password"
				/>
			</div>

			<Button type="submit" color="primary" {loading}>
				{i18n?.update_password?.button_label}
			</Button>

			<Container direction="vertical" gap="small">
				<AuthLink view="sign_in" />
			</Container>

			{#if message}
				<Message>
					{message}
				</Message>
			{/if}
			{#if error}
				<Message color="danger">
					{error}
				</Message>
			{/if}
		</Container>
	</form>
</Theme>

<style>
	form {
		width: 100%;
	}
</style>

// packages/react/src/lib/ui/UpdatePassword.tsx
import Theme from '../Theme';

import React, { useState } from 'react';
import { Button, Container, Input, Label, Message, AuthLink } from '../components';
import { useSupabaseContext } from '../SupabaseProvider';
import { RedirectTo } from '@supabase/auth-ui-shared';

export default function UpdatePassword({ redirectTo }: { redirectTo?: RedirectTo }) {
	const {
		supabaseClient,
		i18n,
		config: { redirectTo: _redirectTo },
	} = useSupabaseContext();

	const [password, setPassword] = useState('');
	const [error, setError] = useState('');
	const [message, setMessage] = useState('');
	const [loading, setLoading] = useState(false);

	const handlePasswordReset = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		setError('');
		setMessage('');
		setLoading(true);
		const { error } = await supabaseClient.auth.updateUser(
			{ password },
			{ emailRedirectTo: redirectTo ?? _redirectTo }
		);
		if (error) setError(error.message);
		else setMessage(i18n?.update_password?.confirmation_text as string);
		setLoading(false);
	};

	const labels = i18n?.update_password;

	return (
		<Theme>
			<form method="post" id="auth-update-password" onSubmit={handlePasswordReset}>
				<Container gap="large" direction={'vertical'}>
					<div>
						<Label htmlFor="password">{labels?.password_label}</Label>
						<Input
							id="password"
							name="password"
							placeholder={labels?.password_label}
							type="password"
							autoFocus
							onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
						/>
					</div>

					<Button type="submit" color="primary" loading={loading}>
						{loading ? labels?.loading_button_label : labels?.button_label}
					</Button>

					<Container direction="vertical" gap="small">
						<AuthLink view="sign_in"></AuthLink>
					</Container>

					{message && <Message>{message}</Message>}
					{error && <Message color="danger">{error}</Message>}
				</Container>
			</form>
		</Theme>
	);
}
