// packages/react/src/lib/Theme.tsx
import { generateCssVariablesFromTheme } from '@supabase/auth-ui-shared';
import { PropsWithChildren } from 'react';
import { useSupabaseContext } from './SupabaseProvider';

export default function Theme({ children }: PropsWithChildren) {
	const {
		appearence: { theme },
	} = useSupabaseContext();

	const style = generateCssVariablesFromTheme(theme).toObject();
	style.display = 'contents';

	return <div style={style}>{children}</div>;
}

// packages/svelte/src/lib/Theme.svelte
<script lang="ts">
	import { generateCssVariablesFromTheme } from '@supabase/auth-ui-shared';
	import { getSupabaseContext } from './SupabaseProvider.svelte';

	const {
		appearence: { theme }
	} = getSupabaseContext();
</script>

<div style={generateCssVariablesFromTheme(theme).toInlineStyleString()}>
	<slot />
</div>

<style>
	div {
		display: contents;
	}
</style>
