// packages/react/src/lib/auth/interfaces/SocialAuth.tsx
import { Provider, SupabaseClient } from '@supabase/supabase-js';
import { useState } from 'react';
import {
  I18nVariables,
  ProviderScopes,
  SocialLayoutType,
  SOCIAL_LAYOUTS,
  template,
} from '@supabase/auth-ui-shared';
import { Button, Container, Divider } from './../../ui';
import * as SocialIcons from './../Icons.js';

interface SocialAuthProps {
  supabaseClient: SupabaseClient;
  socialLayout?: SocialLayoutType;
  providers?: Provider[];
  providerScopes?: Partial<ProviderScopes>;
  queryParams?: { [key: string]: string };
  redirectTo?: RedirectTo;
  onlyThirdPartyProviders?: boolean;
  view?: 'sign_in' | 'sign_up' | 'magic_link';
  i18n?: I18nVariables;
}

type RedirectTo = undefined | string;

function SocialAuth({
  supabaseClient,
  socialLayout = SOCIAL_LAYOUTS.VERTICAL,
  providers = ['github', 'google', 'azure'],
  providerScopes,
  queryParams,
  redirectTo,
  onlyThirdPartyProviders = true,
  view = 'sign_in',
  i18n,
}: SocialAuthProps) {
  const [loading, setLoading] = useState(false);
  const [, setError] = useState('');

  const verticalSocialLayout = socialLayout === SOCIAL_LAYOUTS.VERTICAL ? true : false;

  const currentView = view === 'magic_link' ? 'sign_in' : view;

  const handleProviderSignIn = async (provider: Provider) => {
    setLoading(true);
    const { error } = await supabaseClient.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo,
        scopes: providerScopes?.[provider],
        queryParams,
      },
    });
    if (error) setError(error.message);
    setLoading(false);
  };

  function capitalize(word: string) {
    const lower = word.toLowerCase();
    return word.charAt(0).toUpperCase() + lower.slice(1);
  }

  return (
    <>
      {providers && providers.length > 0 && (
        <>
          <Container gap="large" direction="vertical">
            <Container
              direction={verticalSocialLayout ? 'vertical' : 'horizontal'}
              gap={verticalSocialLayout ? 'small' : 'medium'}
            >
              {providers.map((provider: Provider) => {
                const AuthIcon = SocialIcons[provider];
                return (
                  <Button
                    key={provider}
                    color="default"
                    icon={AuthIcon ? <AuthIcon /> : ''}
                    loading={loading}
                    onClick={() => handleProviderSignIn(provider)}
                  >
                    {verticalSocialLayout &&
                      template(i18n?.[currentView]?.social_provider_text as string, {
                        provider: capitalize(provider),
                      })}
                  </Button>
                );
              })}
            </Container>
          </Container>
          {!onlyThirdPartyProviders && <Divider />}
        </>
      )}
    </>
  );
}

export { SocialAuth };

// packages/svelte/src/lib/auth/interfaces/SocialAuth.svelte
<script lang="ts">
	import type { SupabaseClient, Provider } from '@supabase/supabase-js';
	import {
		type I18nVariables,
		type SocialLayout,
		type ProviderScopes,
		template
	} from '@supabase/auth-ui-shared';

	import Button from '$lib/ui/Button.svelte';
	import Container from '$lib/ui/Container.svelte';
	import Divider from '$lib/ui/Divider.svelte';
	import Icons from '../Icons.svelte';

	export let supabaseClient: SupabaseClient;
	export let socialLayout: keyof typeof SocialLayout;
	export let redirectTo: string | undefined = undefined;
	export let onlyThirdPartyProviders: boolean;
	export let i18n: I18nVariables;
	export let providers: Provider[] = [];
	export let providerScopes: Partial<ProviderScopes> | undefined;
	export let queryParams: { [key: string]: string } | undefined;

	let error = '';
	let loading = false;

	$: verticalSocialLayout = socialLayout === 'vertical' ? true : false;

	async function handleProviderSignIn(provider: Provider) {
		loading = true;
		error = '';
		const { error: providerSigninError } = await supabaseClient.auth.signInWithOAuth({
			provider,
			options: {
				redirectTo,
				scopes: providerScopes?.[provider],
				queryParams
			}
		});
		if (providerSigninError) error = providerSigninError.message;
		loading = false;
	}

	function capitalize(word: string) {
		return word[0].toUpperCase() + word.slice(1).toLowerCase();
	}

	let iconTitle = (provider: string) =>
		template(i18n['sign_in']?.social_provider_text as string, {
			provider: capitalize(provider)
		});
</script>

{#if providers.length}
	<Container direction="vertical" gap="large">
		<Container
			direction={verticalSocialLayout ? 'vertical' : 'horizontal'}
			gap={verticalSocialLayout ? 'small' : 'medium'}
		>
			{#each providers as provider}
				<Button
					aria-label={iconTitle(provider)}
					on:click={() => handleProviderSignIn(provider)}
					type="submit"
					color="default"
					{loading}
				>
					<Icons {provider} />
					{#if verticalSocialLayout}
						{iconTitle(provider)}
					{/if}
				</Button>
			{/each}
		</Container>
	</Container>
	{#if !onlyThirdPartyProviders}
		<Divider />
	{/if}
{/if}
