// packages/react/src/lib/auth/interfaces/UpdatePassword.tsx
import { SupabaseClient } from '@supabase/supabase-js';
import React, { useState } from 'react';
import { I18nVariables } from '@supabase/auth-ui-shared';
import { Button, Container, Input, Label, Message } from './../../ui';

function UpdatePassword({
  supabaseClient,
  i18n,
}: {
  supabaseClient: SupabaseClient;
  i18n?: I18nVariables;
}) {
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);

  const handlePasswordReset = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError('');
    setMessage('');
    setLoading(true);
    const { error } = await supabaseClient.auth.updateUser({ password });
    if (error) setError(error.message);
    else setMessage(i18n?.update_password?.confirmation_text as string);
    setLoading(false);
  };

  const labels = i18n?.update_password;

  return (
    <form method="post" id="auth-update-password" onSubmit={handlePasswordReset}>
      <Container gap="large" direction={'vertical'}>
        <div>
          <Label htmlFor="password">{labels?.password_label}</Label>
          <Input
            id="password"
            name="password"
            placeholder={labels?.password_label}
            type="password"
            autoFocus
            onChange={(e: React.ChangeEvent<HTMLInputElement>) => setPassword(e.target.value)}
          />
        </div>
        <Button type="submit" color="primary" loading={loading}>
          {loading ? labels?.loading_button_label : labels?.button_label}
        </Button>
        {message && <Message>{message}</Message>}
        {error && <Message color="danger">{error}</Message>}
      </Container>
    </form>
  );
}

export { UpdatePassword };

// packages/svelte/src/lib/auth/interfaces/UpdatePassword.svelte
<script lang="ts">
	import type { SupabaseClient } from '@supabase/supabase-js';

	import Button from '$lib/ui/Button.svelte';
	import Container from '$lib/ui/Container.svelte';
	import Input from '$lib/ui/Input.svelte';
	import Label from '$lib/ui/Label.svelte';
	import Message from '$lib/ui/Message.svelte';
	import Anchor from '$lib/ui/Anchor.svelte';

	import { ViewType, type I18nVariables } from '@supabase/auth-ui-shared';

	export let i18n: I18nVariables;
	export let supabaseClient: SupabaseClient;
	export let authView: ViewType;
	export let showLinks = false;

	let password = '';
	let message = '';
	let error = '';
	let loading = false;

	async function handleSubmit() {
		loading = true;
		error = '';
		message = '';
		const { data, error: resetPasswordError } = await supabaseClient.auth.updateUser({
			password
		});
		if (resetPasswordError) error = resetPasswordError.message;
		else message = i18n.update_password?.confirmation_text as string;
		loading = false;
	}
</script>

<form id="auth-update-password" method="post" on:submit|preventDefault={handleSubmit}>
	<Container direction="vertical" gap="large">
		<Container direction="vertical" gap="large">
			<div>
				<Label for="password">
					{i18n?.update_password?.password_label}
				</Label>
				<Input
					id="password"
					type="password"
					name="password"
					autofocus
					placeholder={i18n?.update_password?.password_label}
					bind:value={password}
					autocomplete="password"
				/>
			</div>
			<Button type="submit" color="primary" {loading}>
				{i18n?.update_password?.button_label}
			</Button>
		</Container>

		{#if showLinks}
			<Anchor
				on:click={(e) => {
					e.preventDefault();
					authView = ViewType.SignIn;
				}}
				href="#auth-sign-in">{i18n?.sign_in?.link_text}</Anchor
			>
		{/if}
		{#if message}
			<Message>
				{message}
			</Message>
		{/if}
		{#if error}
			<Message color="danger">
				{error}
			</Message>
		{/if}
	</Container>
</form>

<style>
	form {
		width: 100%;
	}
</style>
